# Generated by Django 4.1.7 on 2023-04-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='youtude',
            field=models.URLField(default=True),
        ),
    ]
