# Generated by Django 4.1.7 on 2023-04-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_youtude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='youtude',
        ),
    ]
